name: 'Your Action Name'
description: 'Your Action Description'
inputs:
  npm-auth-token:
    description: 'NPM auth token'
    required: true
  figma-token:
    description: 'Figma token'
    required: true
  figma-file-url:
    description: 'Figma file url'
    required: true
  github-token:
    description: 'Github Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Figma Action
      uses: primer/figma-action@v1.0.0-alpha.2
      with:
        args: 'format=svg outputDir=./src/'
      env:
        FIGMA_FILE_URL: ${{ inputs.figma-file-url }}
        FIGMA_TOKEN: ${{ inputs.figma-token }}

    - name: Checkout action repository
      uses: actions/checkout@v2
      with:
        repository: 'Kinsey-LKJ/iconFlow-Action'
        path: 'action'

    - name: Remove .git directory in action
      run: rm -rf action/.git
      shell: bash

    - name: Copy src files
      run: cp -R ./src action/
      shell: bash

    - name: Copy and rename package.json
      run: cp ./package.json ./action/user-package.json
      shell: bash

    - name: Install action dependencies
      run: cd action && npm install
      shell: bash

    - name: Generate Icons and Build
      run: node action/main.js
      shell: bash

    - name: Publish to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-auth-token }}" > ~/.npmrc
        cd action && npm publish
      shell: bash

    - name: Build Github Pages
      run: cd action && npm run build
      shell: bash

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: ./action/docs
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: 获取分支名称
      id: branch_name
      run: echo "::set-output name=branch::${{ github.ref }}"
      shell: bash

    - name: 处理分支名称
      id: processed_branch_name
      run: echo "::set-output name=processed_branch::$(basename ${{ steps.branch_name.outputs.branch }})"
      shell: bash

    - name: 显示分支名称
      run: echo "当前分支是 ${{ steps.processed_branch_name.outputs.processed_branch }}"
      shell: bash

    - name: Commit and push changes
      run: |
        git config --global user.name "${{github.actor}}"
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git add -A
        git commit -m "Update from action"
        git push "https://${{inputs.github-token}}@github.com/${{ github.repository }}.git" ${{ steps.processed_branch_name.outputs.processed_branch }}
      shell: bash
