name: 'Your Action Name'
description: 'Your Action Description'
inputs:
  npm-auth-token:
    description: 'NPM auth token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Checkout action repository
      uses: actions/checkout@v2
      with:
        repository: 'Kinsey-LKJ/iconFlow-Action'
        path: 'action'

    - name: Copy src files
      run: cp -R ./src action/
      shell: bash

    - name: List directory contents
      run:  ls -l action/src
      shell: bash

    - name: Install action dependencies
      run: cd action && npm install
      shell: bash

    - name: Generate Icons and Build
      run: node action/main.js
      shell: bash

    - name: Publish to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-auth-token }}" > ~/.npmrc
        npm publish
      shell: bash
