name: 'Your Action Name'
description: 'Your Action Description'
inputs:
  npm-auth-token:
    description: 'NPM auth token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy src files
      run: cp -R src ${{ github.action_path }}
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
      working-directory: ${{ github.action_path }}

    - name: Install action dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Generate Icons and Build
      run: node main.js
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Publish to NPM
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-auth-token }}" > ~/.npmrc
        npm publish
      shell: bash
      working-directory: ${{ github.action_path }}
